[package]
name = "regex_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.4"

# Максимальная оптимизация по скорости и минимальному размеру
[profile.release]
opt-level = 3       # Оптимизация по скорости на максимум
lto = true          # Включаем Link-Time Optimization (удаляет мертвый код)
codegen-units = 1   # Собираем одним куском (выжать максимум скорости за счет долгого билда)
panic = "abort"     # Убираем тяжелую систему раскрутки стека ошибок
strip = true        # Удаляем лишние отладочные символы (как u C#)
